version: '3'
networks:
  traefik:
#
services:
  dnsmasq:
    container_name: dnsmasq
    image: micedwards/dnsmasq-gui:arm7 
    ports:
      - 53:53/udp
      - 53:53/tcp
      - 5380:8080
    volumes:
      - $PWD/dnsmasq.conf:/etc/dnsmasq.conf
    networks:
      - traefik
    environment:
      - HTTP_USER:"admin"
      - HTTP_PASS:"12qwaszx@@"
#
