version: '3'
#
services:
  fail2ban:
    container_name: fail2ban
    image: crazymax/fail2ban:latest
    network_mode: "host"
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - $PWD/data:/data
      - $PWD/data/log:/var/log:ro
    env_file:
      - $PWD/fail2ban.env
#    restart: always
