version: '3'


services:

#----------------------------------------------------------------
  portainer:
    container_name: portainer 
    image: portainer/portainer:latest
    command: -H unix:///var/run/docker.sock
    #    restart: always
    ports:
      - 9000:9000
      - 8000:8000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $PWD/portainer_data:/data
#----------------------------------------------------------------
  nextcloud_db:
    image: 'ugeek/mariadb:arm'
    container_name: nextcloud_db
    environment:
      MYSQL_ROOT_PASSWORD: '@rooteomelhor'
      MYSQL_DATABASE: 'nextcloud'
      MYSQL_USER: 'nextcloud'
      MYSQL_PASSWORD: '@supersenha10'
    volumes:
      - $PWD/nextcloud/db:/var/lib/mysql
#    logging:
#      driver: gelf
#      options:
#        gelf-address: "tcp://192.168.2.250:12201"
#        tag: nextcloud
#----------------------------------------------------------------
  nextcloud:
    image: 'nextcloud:latest'
    container_name: nextcloud
    depends_on:
      - nextcloud_db           
      - redis                     
    environment:
      MYSQL_DATABASE: "nextcloud"
      MYSQL_USER: "nextcloud"
      MYSQL_PASSWORD: "@supersenha10"
      MYSQL_HOST: "nextcloud_db"
      NEXTCLOUD_ADMIN_USER: "suseradmin"
      NEXTCLOUD_ADMIN_PASSWORD: "@supersenha10"
      REDIS_HOST: "redis"
      NEXTCLOUD_TRUSTED_DOMAINS: '192.168.2.27'

    links:
      - nextcloud_db:nextcloud_db
      - redis:redis
    volumes:
      - $PWD/nextcloud/container:/var/www/html
      - $PWD/nextcloud/data:/var/www/html/data
#      - $PWD/nextcloud/config.php:/var/www/html/config/config.php
#    ports:
#      - 80:80
#    logging:
#      driver: gelf
#      options:
#        gelf-address: "tcp://192.168.2.250:12201"
#        tag: nextcloud
#----------------------------------------------------------------
  redis:
    image: redis:alpine
    container_name: redis
    volumes:
      - $PWD/nextcloud/data/redis:/data
#    logging:
#      driver: gelf
#      options:
#        gelf-address: "tcp://192.168.2.250:12201"
#        tag: nextcloud
