version: '3'
networks:
  default:
    external:
      name: traefik
services:
#
  nextcloud_db:
    image: 'hypriot/rpi-mysql'
    container_name: nextcloud_db
    environment:
      MYSQL_ROOT_PASSWORD: supersecretpassword
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_PASSWORD: supersecretpassword
    volumes:
      - $PWD/nextcloud/db:/var/lib/mysql
#
  nextcloud:
    image: 'linuxserver/nextcloud'
#    image: 'nextcloud'
    container_name: nextcloud
    environment:
      MYSQL_DATABASE: "nextcloud"
      MYSQL_USER: "nextcloud"
      MYSQL_PASSWORD: "supersecretpassword"
      MYSQL_HOST: "nextcloud_db"
      NEXTCLOUD_ADMIN_USER: "systemcrash"
      NEXTCLOUD_ADMIN_PASSWORD: "*suporte10"
    ports:
      - '80:80'
    links:
      - nextcloud_db:nextcloud_db
    volumes:
      - $PWD/nextcloud/data:/var/www/html
