version: '3'
networks:
  default:
    external:
      name: traefik
volumes:
  nextcloud_data:
#
services:
  nextcloud:
    container_name: nextcloud
    image: armhero/nextcloud
    volumes:
      #- $PWD/nextcloud:/var/www/html  
      - nextcloud_data:/data
    labels:
      - traefik.backend=nextcloud
      - traefik.frontend.rule=Host:nextcloud.nerdseverino.local
      - traefik.port=80      
      - "traefik.http.routers.nextcloud.rule=Host(`nextcloud.nerdseverino.local`)"
        #    ports:
        #      - 8083:80
        #    networks:
        #      - traefik
#
