version: '3'

networks:
  reverse-proxy:
    external: true
    name: reverse-proxy

services:
#
  nextcloud:
    image: 'nextcloud'
    container_name: nextcloud
    environment:
      VIRTUAL_HOST: nextcloudteste.nerdseverino.com.br
      LETSENCRYPT_HOST: nextcloudteste.nerdseverino.com.br
      LETSENCRYPT_EMAIL: machado.computer@gmail.com
      NEXTCLOUD_ADMIN_USER: "administrador"
      NEXTCLOUD_ADMIN_PASSWORD: "@supersenha"
      SQLITE_DATABASE: banco_sqlite
      NEXTCLOUD_TRUSTED_DOMAINS: "192.168.2.27"
   #ports:
     #- '80:80'
    volumes:
      - $PWD/nextcloud/data:/var/www/html
    networks:
      - reverse-proxy
