version: '3'
#
services:
  rpi-monitor:
    container_name: rpi-monitor
    image: michaelmiklis/rpi-monitor:latest
    volumes:
      - $PWD/vc:/opt/vc
      - /boot:/boot
      - /sys:/dockerhost/sys:ro
      - /etc:/dockerhost/etc:ro
      - /proc:/dockerhost/proc:ro
      - /usr/lib:/dockerhost/usr/lib:ro
<<<<<<< HEAD
    devices:
      - "/dev/vchiq:/dev/vchiq" 
#      - "/dev/vcsm:/dev/vcsm"  
=======
>>>>>>> d0c6c1e6e6dce73bbdcc8661a7bbc619ec9458eb
#    restart: unless-stopped
    ports:
      - 8888:8888
    labels:
      - traefik.backend=rpimonitor
      - traefik.frontend.rule=Host:rpimonitor.nerdseverino.local
      - traefik.port=8888
      - "traefik.http.routers.rpimonitor.rule=Host(`rpimonitor.nerdseverino.local`)"
#
